var annotated_dup =
[
    [ "ecl", "namespaceecl.html", "namespaceecl" ],
    [ "chunk_info", "structchunk__info.html", "structchunk__info" ],
    [ "CoreDebug_Type", "structCoreDebug__Type.html", "structCoreDebug__Type" ],
    [ "dummy_allocator", "structdummy__allocator.html", "structdummy__allocator" ],
    [ "dummy_data", "structdummy__data.html", "structdummy__data" ],
    [ "dummy_type", "structdummy__type.html", "structdummy__type" ],
    [ "DWT_Type", "structDWT__Type.html", "structDWT__Type" ],
    [ "exactly_block", "structexactly__block.html", "structexactly__block" ],
    [ "gpio_tests", "structgpio__tests.html", "structgpio__tests" ],
    [ "less_than_block", "structless__than__block.html", "structless__than__block" ],
    [ "mock_aux", "structmock__aux.html", "structmock__aux" ],
    [ "mock_mut", "structmock__mut.html", "structmock__mut" ],
    [ "mock_power_pin", "structmock__power__pin.html", "structmock__power__pin" ],
    [ "mock_type1", "structmock__type1.html", "structmock__type1" ],
    [ "mock_type2", "structmock__type2.html", "structmock__type2" ],
    [ "mock_type3", "structmock__type3.html", "structmock__type3" ],
    [ "mock_type4", "structmock__type4.html", "structmock__type4" ],
    [ "more_than_block", "structmore__than__block.html", "structmore__than__block" ],
    [ "pin_info", "structpin__info.html", "structpin__info" ],
    [ "pool_mock", "classpool__mock.html", "classpool__mock" ],
    [ "SCB_Type", "structSCB__Type.html", "structSCB__Type" ],
    [ "test_arg", "structtest__arg.html", "structtest__arg" ],
    [ "test_type", "structtest__type.html", "structtest__type" ],
    [ "tmr_cb", "structtmr__cb.html", "structtmr__cb" ]
];