var hierarchy =
[
    [ "ecl::adc< dev >", "classecl_1_1adc.html", null ],
    [ "ecl::adc_cfg< dev >", "structecl_1_1adc__cfg.html", null ],
    [ "ecl::adc_irq_dispatcher", "classecl_1_1adc__irq__dispatcher.html", null ],
    [ "ecl::aux", "classecl_1_1aux.html", [
      [ "mock_aux", "structmock__aux.html", null ]
    ] ],
    [ "ecl::sensor::bh1750< i2c_dev, address >", "classecl_1_1sensor_1_1bh1750.html", null ],
    [ "ecl::binary_semaphore", "classecl_1_1binary__semaphore.html", null ],
    [ "ecl::sdspi< spi_dev, gpio_cs >::ctx_type::block_type", "structecl_1_1sdspi_1_1ctx__type_1_1block__type.html", null ],
    [ "ecl::bus_pipe< GBus >", "classecl_1_1bus__pipe.html", null ],
    [ "ecl::channel_group< trig, chans >", "structecl_1_1channel__group.html", null ],
    [ "ecl::channel_group_exti_trigger< edge, chans >", "structecl_1_1channel__group__exti__trigger.html", null ],
    [ "ecl::channel_group_sw_trigger< chans >", "structecl_1_1channel__group__sw__trigger.html", null ],
    [ "chunk_info", "structchunk__info.html", null ],
    [ "ecl::console_driver", "classecl_1_1console__driver.html", null ],
    [ "CoreDebug_Type", "structCoreDebug__Type.html", null ],
    [ "ecl::cs43l22< I2c, I2s, Rst_gpio >", "classecl_1_1cs43l22.html", null ],
    [ "ecl::fs::dir_descriptor", "classecl_1_1fs_1_1dir__descriptor.html", [
      [ "ecl::fat::dir", "classecl_1_1fat_1_1dir.html", null ]
    ] ],
    [ "ecl::dispatcher_timer", "structecl_1_1dispatcher__timer.html", null ],
    [ "ecl::dma_wrap_base< Impl >", "classecl_1_1dma__wrap__base.html", null ],
    [ "ecl::dma_wrap_base< dma_wrap< Channel > >", "classecl_1_1dma__wrap__base.html", [
      [ "ecl::dma_wrap< Stream, Channel >", "structecl_1_1dma__wrap.html", null ]
    ] ],
    [ "ecl::dma_wrap_base< dma_wrap< Stream, Channel > >", "classecl_1_1dma__wrap__base.html", [
      [ "ecl::dma_wrap< Stream, Channel >", "structecl_1_1dma__wrap.html", null ]
    ] ],
    [ "dummy_allocator< T >", "structdummy__allocator.html", null ],
    [ "dummy_data", "structdummy__data.html", null ],
    [ "dummy_type", "structdummy__type.html", null ],
    [ "DWT_Type", "structDWT__Type.html", null ],
    [ "ecl::empty_gpio", "structecl_1_1empty__gpio.html", null ],
    [ "exactly_block", "structexactly__block.html", null ],
    [ "ecl::explode_chunk_impl< S, B, L, c >", "structecl_1_1explode__chunk__impl.html", null ],
    [ "ecl::explode_chunk_impl< S, B, 0, c... >", "structecl_1_1explode__chunk__impl_3_01S_00_01B_00_010_00_01c_8_8_8_01_4.html", null ],
    [ "ecl::exploded_string< c >", "structecl_1_1exploded__string.html", null ],
    [ "ecl::exti_manager", "classecl_1_1exti__manager.html", [
      [ "ecl::exti_irq_proxy", "structecl_1_1exti__irq__proxy.html", null ]
    ] ],
    [ "ecl::extractor< chs >", "structecl_1_1extractor.html", null ],
    [ "ecl::sensor::fc28< PowerPin >", "classecl_1_1sensor_1_1fc28.html", null ],
    [ "ecl::fs::file_descriptor", "classecl_1_1fs_1_1file__descriptor.html", [
      [ "ecl::fat::file", "classecl_1_1fat_1_1file.html", null ]
    ] ],
    [ "ecl::fs::fs_descriptor< Mount, Fs >", "classecl_1_1fs_1_1fs__descriptor.html", null ],
    [ "ecl::generic_bus< PBus >", "classecl_1_1generic__bus.html", null ],
    [ "ecl::gpio< Port, Pin >", "classecl_1_1gpio.html", null ],
    [ "ecl::gpio_list< Gs >", "structecl_1_1gpio__list.html", null ],
    [ "gpio_tests< Ts >", "structgpio__tests.html", null ],
    [ "ecl::greeter", "structecl_1_1greeter.html", null ],
    [ "ecl::exti_manager::handler", "classecl_1_1exti__manager_1_1handler.html", null ],
    [ "ecl::hm10_sync< Uart, Serial >", "classecl_1_1hm10__sync.html", null ],
    [ "ecl::sensor::htu21d< i2c_dev >", "classecl_1_1sensor_1_1htu21d.html", null ],
    [ "ecl::i2c_bus< dev >", "classecl_1_1i2c__bus.html", null ],
    [ "ecl::i2c_bus_cfg< dev >", "structecl_1_1i2c__bus__cfg.html", null ],
    [ "ecl::i2c_config< dev, mode, clock_speed, operation_mode, duty_cycle, own_address, ack, ack_addr >", "structecl_1_1i2c__config.html", null ],
    [ "ecl::fs::inode", "classecl_1_1fs_1_1inode.html", [
      [ "ecl::fat::dir_inode", "classecl_1_1fat_1_1dir__inode.html", null ],
      [ "ecl::fat::file_inode", "classecl_1_1fat_1_1file__inode.html", null ]
    ] ],
    [ "ecl::iostream< IO_device >", "classecl_1_1iostream.html", null ],
    [ "ecl::iostream_initializer", "structecl_1_1iostream__initializer.html", null ],
    [ "ecl::istream< IO_device >", "classecl_1_1istream.html", null ],
    [ "less_than_block", "structless__than__block.html", null ],
    [ "ecl::list< T, Mptr >", "classecl_1_1list.html", null ],
    [ "ecl::list_iter< T, Mptr >", "classecl_1_1list__iter.html", null ],
    [ "ecl::list_node", "classecl_1_1list__node.html", null ],
    [ "measurement", "structmeasurement.html", null ],
    [ "ecl::mgmt_configurator< dev, mode >", "classecl_1_1mgmt__configurator.html", null ],
    [ "ecl::mgmt_configurator< dev, adc_mgmt_mode::dma >", "classecl_1_1mgmt__configurator_3_01dev_00_01adc__mgmt__mode_1_1dma_01_4.html", null ],
    [ "ecl::mgmt_configurator< dev, adc_mgmt_mode::irq >", "classecl_1_1mgmt__configurator_3_01dev_00_01adc__mgmt__mode_1_1irq_01_4.html", null ],
    [ "mock_mut", "structmock__mut.html", null ],
    [ "mock_power_pin", "structmock__power__pin.html", null ],
    [ "mock_type1", "structmock__type1.html", null ],
    [ "mock_type2", "structmock__type2.html", null ],
    [ "mock_type3", "structmock__type3.html", null ],
    [ "mock_type4", "structmock__type4.html", null ],
    [ "more_than_block", "structmore__than__block.html", null ],
    [ "ecl::mutex", "classecl_1_1mutex.html", null ],
    [ "ecl::native_thread", "classecl_1_1native__thread.html", null ],
    [ "ecl::ostream< IO_device >", "classecl_1_1ostream.html", null ],
    [ "ecl::fs::path_handle", "classecl_1_1fs_1_1path__handle.html", [
      [ "ecl::fs::path_erased< Alloc >", "classecl_1_1fs_1_1path__erased.html", null ]
    ] ],
    [ "ecl::fs::path_iter", "classecl_1_1fs_1_1path__iter.html", null ],
    [ "ecl::pcd8544< Spi, Cs_gpio, Mode_gpio, Rst_gpio >", "classecl_1_1pcd8544.html", null ],
    [ "ecl::fat::petit< Block >", "classecl_1_1fat_1_1petit.html", null ],
    [ "ecl::gpio_hw::pin_bin< Gn, Gns >", "structecl_1_1gpio__hw_1_1pin__bin.html", null ],
    [ "ecl::gpio_hw::pin_bin< Gn >", "structecl_1_1gpio__hw_1_1pin__bin_3_01Gn_01_4.html", null ],
    [ "pin_info", "structpin__info.html", null ],
    [ "ecl::platform_console", "classecl_1_1platform__console.html", null ],
    [ "ecl::point", "classecl_1_1point.html", null ],
    [ "ecl::pool_allocator< T >", "classecl_1_1pool__allocator.html", null ],
    [ "ecl::pool_allocator< uint8_t >", "classecl_1_1pool__allocator.html", null ],
    [ "ecl::pool_base", "classecl_1_1pool__base.html", [
      [ "ecl::pool< blk_sz, blk_cnt >", "classecl_1_1pool.html", null ],
      [ "ecl::pool< get_alloc_blk_size(), 256 >", "classecl_1_1pool.html", null ],
      [ "pool_mock", "classpool__mock.html", null ]
    ] ],
    [ "ecl::mmio::reg< Mut, addr, offset, width >", "structecl_1_1mmio_1_1reg.html", null ],
    [ "ecl::mmio::ro_mut", "structecl_1_1mmio_1_1ro__mut.html", [
      [ "ecl::mmio::rw_mut", "structecl_1_1mmio_1_1rw__mut.html", null ]
    ] ],
    [ "ecl::safe_storage< T >", "structecl_1_1safe__storage.html", null ],
    [ "ecl::safe_storage< adc_evh >", "structecl_1_1safe__storage.html", null ],
    [ "ecl::safe_storage< binary_semaphore >", "structecl_1_1safe__storage.html", null ],
    [ "ecl::safe_storage< bus_handler >", "structecl_1_1safe__storage.html", null ],
    [ "ecl::safe_storage< ctx >", "structecl_1_1safe__storage.html", null ],
    [ "ecl::safe_storage< ctx_type >", "structecl_1_1safe__storage.html", null ],
    [ "ecl::safe_storage< ecl::binary_semaphore >", "structecl_1_1safe__storage.html", null ],
    [ "ecl::safe_storage< ecl::list >", "structecl_1_1safe__storage.html", null ],
    [ "ecl::safe_storage< handler_fn >", "structecl_1_1safe__storage.html", null ],
    [ "ecl::safe_storage< serial_chunks >", "structecl_1_1safe__storage.html", null ],
    [ "SCB_Type", "structSCB__Type.html", null ],
    [ "ecl::sdspi< spi_dev, gpio_cs >", "classecl_1_1sdspi.html", null ],
    [ "ecl::sdspi_card_info", "structecl_1_1sdspi__card__info.html", null ],
    [ "ecl::sdspi_state", "structecl_1_1sdspi__state.html", null ],
    [ "ecl::semaphore", "classecl_1_1semaphore.html", null ],
    [ "ecl::serial< PBus, buf_size >", "classecl_1_1serial.html", null ],
    [ "ecl::shared_allocation_size< T, Alloc >", "structecl_1_1shared__allocation__size.html", null ],
    [ "ecl::shared_ptr< T >", "classecl_1_1shared__ptr.html", null ],
    [ "ecl::shared_ptr< inode >", "classecl_1_1shared__ptr.html", null ],
    [ "ecl::shared_ptr< path_handle >", "classecl_1_1shared__ptr.html", null ],
    [ "ecl::skel::spi< ch >", "classecl_1_1skel_1_1spi.html", null ],
    [ "ecl::spi< ch >", "classecl_1_1spi.html", [
      [ "ecl::spi_irq_proxy< ch >", "structecl_1_1spi__irq__proxy.html", null ]
    ] ],
    [ "ecl::spi_cfg< ch >", "structecl_1_1spi__cfg.html", null ],
    [ "ecl::skel::spi_cfg< ch >", "structecl_1_1skel_1_1spi__cfg.html", null ],
    [ "ecl::spi_i2s_bus< dev >", "classecl_1_1spi__i2s__bus.html", null ],
    [ "ecl::spi_i2s_cfg< dev >", "structecl_1_1spi__i2s__cfg.html", null ],
    [ "ecl::spinlock", "classecl_1_1spinlock.html", null ],
    [ "test_arg", "structtest__arg.html", null ],
    [ "test_type", "structtest__type.html", null ],
    [ "tmr_cb", "structtmr__cb.html", null ],
    [ "ecl::uart< ch >", "classecl_1_1uart.html", [
      [ "ecl::uart_irq_proxy< ch >", "structecl_1_1uart__irq__proxy.html", null ]
    ] ],
    [ "ecl::uart_bus< dev >", "classecl_1_1uart__bus.html", null ],
    [ "ecl::usart_bus< dev >", "classecl_1_1usart__bus.html", null ],
    [ "ecl::usart_cfg< dev >", "structecl_1_1usart__cfg.html", null ],
    [ "ecl::fs::vfs< Fs >", "classecl_1_1fs_1_1vfs.html", null ],
    [ "ecl::weak_ptr< T >", "classecl_1_1weak__ptr.html", null ],
    [ "ecl::weak_ptr< inode >", "classecl_1_1weak__ptr.html", null ],
    [ "ecl::mmio::wo_mut", "structecl_1_1mmio_1_1wo__mut.html", null ]
];