var namespaceecl =
[
    [ "gpio_hw", "namespaceecl_1_1gpio__hw.html", "namespaceecl_1_1gpio__hw" ],
    [ "mmio", "namespaceecl_1_1mmio.html", "namespaceecl_1_1mmio" ],
    [ "os", "namespaceecl_1_1os.html", null ],
    [ "sensor", "namespaceecl_1_1sensor.html", "namespaceecl_1_1sensor" ],
    [ "adc", "classecl_1_1adc.html", "classecl_1_1adc" ],
    [ "adc_cfg", "structecl_1_1adc__cfg.html", null ],
    [ "adc_cfg< adc_dev::dev1 >", "structecl_1_1adc__cfg_3_01adc__dev_1_1dev1_01_4.html", "structecl_1_1adc__cfg_3_01adc__dev_1_1dev1_01_4" ],
    [ "adc_irq_dispatcher", "classecl_1_1adc__irq__dispatcher.html", "classecl_1_1adc__irq__dispatcher" ],
    [ "aux", "classecl_1_1aux.html", "classecl_1_1aux" ],
    [ "binary_semaphore", "classecl_1_1binary__semaphore.html", "classecl_1_1binary__semaphore" ],
    [ "bus_pipe", "classecl_1_1bus__pipe.html", "classecl_1_1bus__pipe" ],
    [ "channel_group", "structecl_1_1channel__group.html", "structecl_1_1channel__group" ],
    [ "channel_group_exti_trigger", "structecl_1_1channel__group__exti__trigger.html", "structecl_1_1channel__group__exti__trigger" ],
    [ "channel_group_sw_trigger", "structecl_1_1channel__group__sw__trigger.html", "structecl_1_1channel__group__sw__trigger" ],
    [ "console_driver", "classecl_1_1console__driver.html", "classecl_1_1console__driver" ],
    [ "cs43l22", "classecl_1_1cs43l22.html", "classecl_1_1cs43l22" ],
    [ "dispatcher_timer", "structecl_1_1dispatcher__timer.html", "structecl_1_1dispatcher__timer" ],
    [ "dma_wrap", "structecl_1_1dma__wrap.html", "structecl_1_1dma__wrap" ],
    [ "dma_wrap_base", "classecl_1_1dma__wrap__base.html", "classecl_1_1dma__wrap__base" ],
    [ "dummy_platform_bus", "classecl_1_1dummy__platform__bus.html", "classecl_1_1dummy__platform__bus" ],
    [ "empty_gpio", "structecl_1_1empty__gpio.html", "structecl_1_1empty__gpio" ],
    [ "exti_manager", "classecl_1_1exti__manager.html", "classecl_1_1exti__manager" ],
    [ "extractor", "structecl_1_1extractor.html", "structecl_1_1extractor" ],
    [ "generic_bus", "classecl_1_1generic__bus.html", "classecl_1_1generic__bus" ],
    [ "gpio", "classecl_1_1gpio.html", "classecl_1_1gpio" ],
    [ "gpio_list", "structecl_1_1gpio__list.html", "structecl_1_1gpio__list" ],
    [ "hm10_sync", "classecl_1_1hm10__sync.html", "classecl_1_1hm10__sync" ],
    [ "i2c_bus", "classecl_1_1i2c__bus.html", "classecl_1_1i2c__bus" ],
    [ "i2c_bus_cfg", "structecl_1_1i2c__bus__cfg.html", null ],
    [ "i2c_bus_cfg< i2c_device::wire0 >", "structecl_1_1i2c__bus__cfg_3_01i2c__device_1_1wire0_01_4.html", "structecl_1_1i2c__bus__cfg_3_01i2c__device_1_1wire0_01_4" ],
    [ "i2c_config", "structecl_1_1i2c__config.html", "structecl_1_1i2c__config" ],
    [ "iostream", "classecl_1_1iostream.html", "classecl_1_1iostream" ],
    [ "iostream_initializer", "structecl_1_1iostream__initializer.html", "structecl_1_1iostream__initializer" ],
    [ "istream", "classecl_1_1istream.html", "classecl_1_1istream" ],
    [ "list", "classecl_1_1list.html", "classecl_1_1list" ],
    [ "list_iter", "classecl_1_1list__iter.html", "classecl_1_1list__iter" ],
    [ "list_node", "classecl_1_1list__node.html", "classecl_1_1list__node" ],
    [ "mgmt_configurator", "classecl_1_1mgmt__configurator.html", null ],
    [ "mgmt_configurator< dev, adc_mgmt_mode::dma >", "classecl_1_1mgmt__configurator_3_01dev_00_01adc__mgmt__mode_1_1dma_01_4.html", "classecl_1_1mgmt__configurator_3_01dev_00_01adc__mgmt__mode_1_1dma_01_4" ],
    [ "mgmt_configurator< dev, adc_mgmt_mode::irq >", "classecl_1_1mgmt__configurator_3_01dev_00_01adc__mgmt__mode_1_1irq_01_4.html", "classecl_1_1mgmt__configurator_3_01dev_00_01adc__mgmt__mode_1_1irq_01_4" ],
    [ "mutex", "classecl_1_1mutex.html", "classecl_1_1mutex" ],
    [ "native_thread", "classecl_1_1native__thread.html", "classecl_1_1native__thread" ],
    [ "ostream", "classecl_1_1ostream.html", "classecl_1_1ostream" ],
    [ "pcd8544", "classecl_1_1pcd8544.html", "classecl_1_1pcd8544" ],
    [ "platform_console", "classecl_1_1platform__console.html", "classecl_1_1platform__console" ],
    [ "point", "classecl_1_1point.html", "classecl_1_1point" ],
    [ "pool", "classecl_1_1pool.html", "classecl_1_1pool" ],
    [ "pool_allocator", "classecl_1_1pool__allocator.html", "classecl_1_1pool__allocator" ],
    [ "pool_base", "classecl_1_1pool__base.html", "classecl_1_1pool__base" ],
    [ "safe_storage", "classecl_1_1safe__storage.html", "classecl_1_1safe__storage" ],
    [ "sd_spi", "classecl_1_1sd__spi.html", "classecl_1_1sd__spi" ],
    [ "semaphore", "classecl_1_1semaphore.html", "classecl_1_1semaphore" ],
    [ "serial", "classecl_1_1serial.html", "classecl_1_1serial" ],
    [ "shared_allocation_size", "structecl_1_1shared__allocation__size.html", "structecl_1_1shared__allocation__size" ],
    [ "shared_ptr", "classecl_1_1shared__ptr.html", "classecl_1_1shared__ptr" ],
    [ "spi_i2s_bus", "classecl_1_1spi__i2s__bus.html", "classecl_1_1spi__i2s__bus" ],
    [ "spi_i2s_cfg", "structecl_1_1spi__i2s__cfg.html", null ],
    [ "spi_i2s_cfg< spi_device::bus3 >", "structecl_1_1spi__i2s__cfg_3_01spi__device_1_1bus3_01_4.html", "structecl_1_1spi__i2s__cfg_3_01spi__device_1_1bus3_01_4" ],
    [ "spinlock", "classecl_1_1spinlock.html", "classecl_1_1spinlock" ],
    [ "uart_bus", "classecl_1_1uart__bus.html", "classecl_1_1uart__bus" ],
    [ "usart_bus", "classecl_1_1usart__bus.html", "classecl_1_1usart__bus" ],
    [ "usart_cfg", "structecl_1_1usart__cfg.html", null ],
    [ "usart_cfg< usart_device::dev1 >", "structecl_1_1usart__cfg_3_01usart__device_1_1dev1_01_4.html", "structecl_1_1usart__cfg_3_01usart__device_1_1dev1_01_4" ],
    [ "usart_cfg< usart_device::dev3 >", "structecl_1_1usart__cfg_3_01usart__device_1_1dev3_01_4.html", "structecl_1_1usart__cfg_3_01usart__device_1_1dev3_01_4" ],
    [ "weak_ptr", "classecl_1_1weak__ptr.html", "classecl_1_1weak__ptr" ]
];